twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        site_name: 'citizenz'
        site_url: 'citizenz.info'
        site_urlFull: 'https://www.citizenz.info'
        site_mail: 'contact@citizenz.info'
        site_author: 'Olivier Prieur'
